version: '3'
services:
  whoami:
    image: traefik/whoami
    container_name: whoami
    hostname: whoami
    labels:
      # Traefik Labels
      - "traefik.enable=true"
      # HTTPS Labels
      - "traefik.http.routers.whoami.rule=Host(`localhost`)"
      - "traefik.http.routers.whoami.entrypoints=web-secure"
      - "traefik.http.routers.whoami.middlewares=default-headers@file"
      - "traefik.http.routers.whoami.service=whoami"
      - "traefik.http.routers.whoami.tls=true"
      - "traefik.http.services.whoami.loadbalancer.server.port=80"
